<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\YAT.Infrastructure\YAT.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\YAT.Application\YAT.Application.csproj" />
    <ProjectReference Include="..\..\src\YAT.Domain\YAT.Domain.csproj" />
  </ItemGroup>

</Project>
